# The url exposed on the internet (ex via reverse proxy)
baseURL: http://localhost:7432 # Exposed url no trailing '/'

bridgeApiEndPoint: OVERRIDE_ME

pryv: 
  serviceInfoUrl: https://demo.datasafe.dev/reg/service/info
  appId: bridge-chartneo
  mainStream: 
    id: chartneo
    name: Chartneo
  permissions:
    - streamId: chartneo
      level: manage
      defaultName: Chartneo
  consentMessage: Connect HDS with Chartneo. -- to be detailed -- 


start:
  # if numProcesses=0 launch 1 process per CPU
  # if numProcesses>0 launch exactly numProcess processes
  # if numProcesses<0 launch max(numCPU + numProcess, 1) process(es)
  numProcesses: 0 

server:
  port: 7432
  host: '0.0.0.0'

  logs: 
  console: 
    active: true
    level: info
    format: 
      color: true
      time: true
      aligned: true
  file: 
    active: true
    path: application.log
